### PR TITLE
Use maxLength in Error message

### LINKED ISSUE #30: Possbile `nil` reference `JSONSchemaLengthConstraint>>#validate:`
The `maxLength` exceeded message in `JSONSchemaLengthConstraint>>#validate:` references `minLength` which might be nil:
https://github.com/zweidenker/JSONSchema/blob/ea3a9e86281611d76c9804060f27cf79a4ca145a/source/JSONSchema-Core.package/JSONSchemaLengthConstraint.class/instance/validate..st#L14

Also `maxLength` has to be used here anyway.

### PR DESCRIPTION
**Pull request by udoschneider**
Fixes  #30

### CODE REVIEW

**Comment by noha** [comment]
Thanks again. I think there is no need to make an issue if you provide a pull request. Just waste of time ;)

**Comment by udoschneider** [comment]
> Thanks again. I think there is no need to make an issue if you provide a pull request. Just waste of time ;)
Will (not :-) ) do. I'm just used to other workflows where *every* pull/merge request need to be associated with an "issue" (tagged as feature, bug ...).

**Comment by noha** [comment]
We had that, too. Then recognized that the issue right before a pull request only wastes time and does not serve a purpose hence to be removed ;)

**Comment by udoschneider** [comment]
I can live with less work ... no problem at all.

Taking care of max/min constraints for objects and arrays no. And then combination support (anyOf and friends) which is the thing I ultimately need ...

**Comment by noha** [comment]
If you can say what you will do and what you need I can try to help

**Comment by udoschneider** [comment]
Thanks for the offer. Right now I think I have a pretty good grasp on the code and how to achieve what I want.

I may have to ask for possible refactorings/class renames/class reorgs though. From what I can see all the different size constraints for different entity types are/will be implemented in disjoint classes. I think we can reorg this into a common superclass where all it's subclasses only need to provide custom error messages and `definitionProperties`.

**Pull request merged**
